name = "api"
compatibility_date = "2024-04-03"

[[durable_objects.bindings]]
name = "CACHE"
class_name = "DurableObjectRateLimiter"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["DurableObjectRateLimiter"]
