import { z } from "zod";

export const cinemarkSchema = z.object({
  TimeStamp: z.number(),
  Cinemas: z.array(
    z.union([
      z.object({
        Id: z.number(),
        Name: z.string(),
        City: z.string(),
        Address: z.string(),
        Description: z.string(),
        Features: z.string(),
        decLatitude: z.string(),
        decLongitude: z.string(),
        Metro: z.string(),
        Buses: z.string(),
        Manager: z.string(),
        URLThumb: z.string(),
        URLGoogleMaps: z.string(),
      }),
      z.object({
        Id: z.number(),
        Name: z.string(),
        City: z.string(),
        Address: z.string(),
        Description: z.string(),
        Features: z.string(),
        decLatitude: z.string(),
        decLongitude: z.string(),
        Metro: z.null(),
        Buses: z.null(),
        Manager: z.string(),
        URLThumb: z.string(),
        URLGoogleMaps: z.string(),
      }),
    ]),
  ),
  Films: z.array(
    z.union([
      z.object({
        Name: z.string(),
        Id: z.string(),
        Rating: z.string(),
        FilmCode: z.string(),
        Distributor: z.string(),
        Description: z.string(),
        Duration: z.string(),
        Category: z.string(),
        OpeningDate: z.string(),
        URLPoster: z.string(),
        URLTrailerAmazon: z.string(),
        URLTrailerYoutube: z.string(),
        TWHashTag: z.string(),
        PersonList: z.array(z.object({ Type: z.string(), Name: z.string() })),
        AttributeList: z.array(z.unknown()),
        FormatList: z.array(z.string()),
        CinemaList: z.array(z.number()),
        MovieList: z.array(
          z.object({
            Id: z.number(),
            MovieId: z.string(),
            FormatId: z.string(),
            Format: z.string(),
            Version: z.string(),
            CinemaList: z.array(
              z.object({
                Id: z.number(),
                SessionList: z.array(
                  z.object({
                    i: z.number(),
                    f: z.number(),
                    s: z.number(),
                    d: z.string(),
                    p: z.number(),
                    Capacity: z.number(),
                  }),
                ),
              }),
            ),
          }),
        ),
        BillboardTagList: z.array(z.number()),
        FilmBannerList: z.array(z.number()),
        Theme: z.null(),
        CorporateId: z.string(),
      }),
      z.object({
        Name: z.string(),
        Id: z.string(),
        Rating: z.string(),
        FilmCode: z.string(),
        Distributor: z.string(),
        Description: z.string(),
        Duration: z.string(),
        Category: z.string(),
        OpeningDate: z.string(),
        URLPoster: z.string(),
        URLTrailerAmazon: z.string(),
        URLTrailerYoutube: z.string(),
        TWHashTag: z.string(),
        PersonList: z.array(z.object({ Type: z.string(), Name: z.string() })),
        AttributeList: z.array(z.number()),
        FormatList: z.array(z.string()),
        CinemaList: z.array(z.number()),
        MovieList: z.array(
          z.object({
            Id: z.number(),
            MovieId: z.string(),
            FormatId: z.string(),
            Format: z.string(),
            Version: z.string(),
            CinemaList: z.array(
              z.object({
                Id: z.number(),
                SessionList: z.array(
                  z.object({
                    i: z.number(),
                    f: z.number(),
                    s: z.number(),
                    d: z.string(),
                    p: z.number(),
                    Capacity: z.number(),
                  }),
                ),
              }),
            ),
          }),
        ),
        BillboardTagList: z.array(z.number()),
        FilmBannerList: z.array(z.number()),
        Theme: z.null(),
        CorporateId: z.string(),
      }),
    ]),
  ),
  ComingSoonFilms: z.array(
    z.object({
      Id: z.number(),
      Name: z.string(),
      Description: z.string(),
      OpeningDate: z.string(),
      URLTrailerYoutube: z.string(),
      Duration: z.number(),
      Category: z.string(),
      Rating: z.string(),
      URLPoster: z.string(),
      TWHashTag: z.null(),
    }),
  ),
  Highlights: z.array(
    z.object({
      Id: z.number(),
      strTitle: z.string(),
      strDescription: z.string(),
      bitButton: z.boolean(),
      strButtonText: z.string(),
      strButtonAction: z.string(),
      strURLImage: z.string(),
      strURLImageMobile: z.string(),
      jsonLoyaltyLevel: z.array(z.number()),
    }),
  ),
  Billboards: z.array(
    z.union([
      z.object({
        BillboardId: z.number(),
        Title: z.string(),
        Formats: z.array(z.string()),
        jsonTagsId: z.array(z.number()),
      }),
      z.object({
        BillboardId: z.number(),
        Title: z.string(),
        Formats: z.null(),
        jsonTagsId: z.array(z.number()),
      }),
    ]),
  ),
  FilmsBanners: z.array(
    z.object({
      ID: z.number(),
      intPosition: z.number(),
      strLink: z.string(),
      strURLImagePath: z.string(),
    }),
  ),
  SectionBanners: z.array(
    z.object({
      ID: z.number(),
      intPosition: z.number(),
      strSectionTitle: z.string(),
      strLink: z.string(),
      strURLImagePath: z.string(),
      jsonLoyaltyLevel: z.array(z.number()),
    }),
  ),
  FilmsAttributes: z.array(
    z.union([
      z.object({
        intAttributeId: z.number(),
        strTitle: z.string(),
        strPosterMessage: z.string(),
        strPosterCss: z.string(),
        strSessionMessage: z.string(),
        strSessionCss: z.string(),
        strPopinMessage: z.string(),
        strPopinCss: z.string(),
      }),
      z.object({
        intAttributeId: z.number(),
        strTitle: z.string(),
        strPosterMessage: z.null(),
        strPosterCss: z.null(),
        strSessionMessage: z.null(),
        strSessionCss: z.null(),
        strPopinMessage: z.null(),
        strPopinCss: z.null(),
      }),
    ]),
  ),
});
